name: coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Resolve dependencies
        run: cargo generate-lockfile

      - name: cargo llvm-cov
        run: >
          cargo llvm-cov --locked --all-features
          --codecov
          --output-path codecov.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          file: codecov.json
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
